### ISSUE TITLE
line 258 error

### ISSUE THREAD

**Issue by joerosato** [PocketDock/PocketDockConsole#10]
Keep getting this error after upgrading, then got same error on going back to 9 vs 10. This is the 9 error.

Warning: pack(): Type N: too few arguments in phar:///home/joe/pocketmine-mp/plugins/PocketDockConsole_bcd5d5d31a1c.phar/src/PocketDockConsole/SocksServer.php on line 258

**Comment by Humerus** [comment]
Fixed in #13
