### ISSUE TITLE
can't load plugin

### ISSUE THREAD

**Issue by mtuckerb** [PocketDock/PocketDockConsole#11]
I get 
Warning: stream_socket_accept() expects parameter 1 to be resource, boolean given in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 78

Warning: stream_socket_get_name() expects parameter 1 to be resource, boolean given in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 79

Warning: fread() expects parameter 1 to be resource, boolean given in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 81

Warning: fwrite() expects parameter 1 to be resource, boolean given in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 84

Warning: fclose() expects parameter 1 to be resource, boolean given in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 85

Warning: stream_select(): supplied argument is not a valid stream resource in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 74

Warning: stream_select(): No stream arrays were passed in phar:///home/mtuckerb/MCPE/plugins/PocketDockConsole_v0.0.10.phar/src/PocketDockConsole/SocksServer.php on line 74

**Comment by Humerus** [comment]
Fixed in #13
