### ISSUE TITLE
Unable to connect to server. 

### ISSUE THREAD

**Issue by Midnight-Shadow** [PocketDock/PocketDockConsole#12]
Hello, I like the idea of this plugin, but in the config file, I set the password the same as the server.properties one, and port forwarded port 12121 on my router, and put that port on the config also. When i connect, I see the website, but it doesn't ask me for

**Comment by Midnight-Shadow** [comment]
Oops, hit wrong button!!!! Anyways, when I connect, I see a popup that says unable to connect to server, even though in the real server it says successful connection from xxx.xxx.xx.xxx:xxxxx. What is causing this? I'm using latest development pocketmine soft (tried on MP too, same thing). Can you recreate this problem?

**Comment by Humerus** [comment]
Fixed in #13
